[tool.black]
line-length = 79

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 79
skip_glob = [".github/*", ".idea/*", ".pytest_cache/*", "data/*", "docs/*", "models/*", "venv/*"]

[tool.pytest.ini_options]
filterwarnings = [
    'ignore:the imp module is deprecated:DeprecationWarning',
    'ignore:distutils Version classes are deprecated:DeprecationWarning',
    'ignore:[a-zA-Z]* is deprecated and will be removed in Pillow 10:DeprecationWarning'
]
