name: CI

on: [pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Debug
        run: ls
      - name: Install requirements
        run: pip install black flake8 isort
      - name: Black check formatting
        run: black --verbose --check .
      - name: Check imports using isort
        run: isort -v --check-only .
      - name: Flake8 linting
        run: flake8 -v --ignore=E203 .

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Debug
        run: ls
      - name: Install pip packages
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest --cov --cov-report xml tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Debug
        run: ls
      - name: Install pip packages
        run: pip install -r requirements.txt
      - name: Move to docs folder
        run: cd docs
      - name: Generate docs
        run: |
          sphinx-apidoc -f -o . ..
          make html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/_build/html # The folder the action should deploy.
